ldc2d:
	mpiexec -n 1 python3 ldc.py --baseN 10 --k 2 --dim 2 --nref 1 --Re 1 10 --Rem 1 10 --S 1 --hierarchy uniform --ns-discr hdivbdm --mw-discr BE --mhd-type standard --solver-type lu --linearisation newton
